### ISSUE TITLE
Sigmadsp with Allwinner H3

### ISSUE THREAD

**Issue by mikhalych63** [blus-audio/sigmadsp#90]
I am try to install your project sigmadsp on a nanopi neo air board with Allwinner H3. OS is Armbian Bookworm (Debian) distribution. Now I have achieved that the sigmadsp-backend system service is loading, but with the error "raise BadPinFactory('Unable to load any default pin factory!')" As I understand it, the error is related to managing pins using the gpiozero library, but this library is intended only for Raspberry pi!
How to simply disable this feature: reset and selfboot? At least now my ADAU1467 is normally programmed without using these contacts and I only need a SigmaTCP connection right now?
--

**Comment by elagil** [comment]
Can you tell me where exactly the error is raised? I can catch it then.

**Comment by elagil** [comment]
Please check https://github.com/blus-audio/sigmadsp/pull/91/files#diff-087b879eaae2a27c2a1b33219773cb58af127b8b7f76c62da614808a19c64769R31-R38

It should fix your problem. GPIOs will now be disabled on non-Raspberry Pi platforms. Just update to the latest release v3.0.11.

**Comment by mikhalych63** [comment]
I'll try it tonight. I'll try it tonight.

**Comment by mikhalych63** [comment]
Good! it's working now! Thank you!

**Comment by elagil** [comment]
Great! Happy to hear that.
